"""phase_e_credit_exposure

Revision ID: 168c1e8eb186
Revises: 81ed9bb9a5a6
Create Date: 2026-05-20 22:29:42.684556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '168c1e8eb186'
down_revision: Union[str, Sequence[str], None] = '81ed9bb9a5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_sources', sa.Column('card_outstanding', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('payment_sources', sa.Column('shared_group_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_payment_sources_shared_group_id'), 'payment_sources', ['shared_group_id'], unique=False)
    # ### end Alembic commands ###

    # Data Backfill for phase E
    op.execute("""
        UPDATE payment_sources 
        SET card_outstanding = credit_limit - available_limit 
        WHERE type = 'credit_card' AND credit_limit IS NOT NULL AND available_limit IS NOT NULL
    """)
    op.execute("""
        UPDATE payment_sources 
        SET statement_day = CAST(SUBSTRING(billing_date FROM 9 FOR 2) AS INTEGER)
        WHERE type = 'credit_card' AND billing_date IS NOT NULL AND statement_day IS NULL
    """)
    op.execute("""
        UPDATE payment_sources 
        SET due_day = CAST(SUBSTRING(due_date FROM 9 FOR 2) AS INTEGER)
        WHERE type = 'credit_card' AND due_date IS NOT NULL AND due_day IS NULL
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_sources_shared_group_id'), table_name='payment_sources')
    op.drop_column('payment_sources', 'shared_group_id')
    op.drop_column('payment_sources', 'card_outstanding')
    # ### end Alembic commands ###
