"""update_emi_obligation_schema

Revision ID: 238b1a3561dd
Revises: fa0cb382d9bf
Create Date: 2026-05-20 17:46:19.229587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '238b1a3561dd'
down_revision: Union[str, Sequence[str], None] = 'fa0cb382d9bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emi_obligations', sa.Column('principal_remaining', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('emi_obligations', sa.Column('monthly_emi', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('emi_obligations', sa.Column('linked_pool_id', sa.String(length=36), nullable=True))
    op.add_column('emi_obligations', sa.Column('linked_card_id', sa.String(length=36), nullable=False))
    op.add_column('emi_obligations', sa.Column('next_due_date', sa.String(), nullable=True))
    op.add_column('emi_obligations', sa.Column('emi_status', sa.String(), nullable=False))
    op.drop_index(op.f('ix_emi_obligations_source_id'), table_name='emi_obligations')
    op.drop_index(op.f('ix_emi_obligations_transaction_id'), table_name='emi_obligations')
    op.create_index(op.f('ix_emi_obligations_linked_card_id'), 'emi_obligations', ['linked_card_id'], unique=False)
    op.create_index(op.f('ix_emi_obligations_linked_pool_id'), 'emi_obligations', ['linked_pool_id'], unique=False)
    op.drop_constraint(op.f('emi_obligations_source_id_fkey'), 'emi_obligations', type_='foreignkey')
    op.drop_constraint(op.f('emi_obligations_transaction_id_fkey'), 'emi_obligations', type_='foreignkey')
    op.create_foreign_key(None, 'emi_obligations', 'payment_sources', ['linked_card_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'emi_obligations', 'credit_pools', ['linked_pool_id'], ['id'], ondelete='SET NULL')
    op.drop_column('emi_obligations', 'monthly_payment')
    op.drop_column('emi_obligations', 'transaction_id')
    op.drop_column('emi_obligations', 'source_id')
    op.drop_column('emi_obligations', 'remaining_months')
    op.drop_column('emi_obligations', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emi_obligations', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('emi_obligations', sa.Column('remaining_months', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('emi_obligations', sa.Column('source_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('emi_obligations', sa.Column('transaction_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('emi_obligations', sa.Column('monthly_payment', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'emi_obligations', type_='foreignkey')
    op.drop_constraint(None, 'emi_obligations', type_='foreignkey')
    op.create_foreign_key(op.f('emi_obligations_transaction_id_fkey'), 'emi_obligations', 'transactions', ['transaction_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('emi_obligations_source_id_fkey'), 'emi_obligations', 'payment_sources', ['source_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_emi_obligations_linked_pool_id'), table_name='emi_obligations')
    op.drop_index(op.f('ix_emi_obligations_linked_card_id'), table_name='emi_obligations')
    op.create_index(op.f('ix_emi_obligations_transaction_id'), 'emi_obligations', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_emi_obligations_source_id'), 'emi_obligations', ['source_id'], unique=False)
    op.drop_column('emi_obligations', 'emi_status')
    op.drop_column('emi_obligations', 'next_due_date')
    op.drop_column('emi_obligations', 'linked_card_id')
    op.drop_column('emi_obligations', 'linked_pool_id')
    op.drop_column('emi_obligations', 'monthly_emi')
    op.drop_column('emi_obligations', 'principal_remaining')
    # ### end Alembic commands ###
