"""expand payment source system

Revision ID: 4ad4d82372f2
Revises: f22d07aaab59
Create Date: 2026-05-12 17:53:59.118783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad4d82372f2'
down_revision: Union[str, Sequence[str], None] = 'f22d07aaab59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_sources', sa.Column('account_holder_name', sa.String(), nullable=True))
    op.add_column('payment_sources', sa.Column('account_subtype', sa.String(), nullable=True))
    op.add_column('payment_sources', sa.Column('ifsc_code', sa.String(), nullable=True))
    op.add_column('payment_sources', sa.Column('upi_id', sa.String(), nullable=True))
    op.add_column('payment_sources', sa.Column('linked_bank_name', sa.String(), nullable=True))
    op.add_column('payment_sources', sa.Column('linked_account_id', sa.String(length=36), nullable=True))
    op.add_column('payment_sources', sa.Column('cash_label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_sources', 'cash_label')
    op.drop_column('payment_sources', 'linked_account_id')
    op.drop_column('payment_sources', 'linked_bank_name')
    op.drop_column('payment_sources', 'upi_id')
    op.drop_column('payment_sources', 'ifsc_code')
    op.drop_column('payment_sources', 'account_subtype')
    op.drop_column('payment_sources', 'account_holder_name')
    # ### end Alembic commands ###
