"""add missing model fields

Revision ID: 50a058815260
Revises: 4ad4d82372f2
Create Date: 2026-05-17 16:57:47.433374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a058815260'
down_revision: Union[str, Sequence[str], None] = '4ad4d82372f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_sources', 'linked_account_id')
    op.add_column('transactions', sa.Column('recurring_interval', sa.String(), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('display_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('settings_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'settings_json')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'full_name')
    op.drop_column('transactions', 'recurring_interval')
    op.add_column('payment_sources', sa.Column('linked_account_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
