"""add_phase_d_models_and_fields

Revision ID: 81ed9bb9a5a6
Revises: 238b1a3561dd
Create Date: 2026-05-20 20:41:14.718490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ed9bb9a5a6'
down_revision: Union[str, Sequence[str], None] = '238b1a3561dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('pool_id', sa.String(length=36), nullable=True),
    sa.Column('previous_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('new_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['credit_pools.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['payment_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_logs_id'), 'reconciliation_logs', ['id'], unique=False)
    op.create_index(op.f('ix_reconciliation_logs_pool_id'), 'reconciliation_logs', ['pool_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_logs_source_id'), 'reconciliation_logs', ['source_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_logs_user_id'), 'reconciliation_logs', ['user_id'], unique=False)
    op.add_column('emi_obligations', sa.Column('paid_installments', sa.Integer(), nullable=False))
    op.add_column('emi_obligations', sa.Column('missed_installments', sa.Integer(), nullable=False))
    op.add_column('emi_obligations', sa.Column('credit_restoration_type', sa.String(), nullable=False))
    op.add_column('payment_sources', sa.Column('statement_day', sa.Integer(), nullable=True))
    op.add_column('payment_sources', sa.Column('due_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_sources', 'due_day')
    op.drop_column('payment_sources', 'statement_day')
    op.drop_column('emi_obligations', 'credit_restoration_type')
    op.drop_column('emi_obligations', 'missed_installments')
    op.drop_column('emi_obligations', 'paid_installments')
    op.drop_index(op.f('ix_reconciliation_logs_user_id'), table_name='reconciliation_logs')
    op.drop_index(op.f('ix_reconciliation_logs_source_id'), table_name='reconciliation_logs')
    op.drop_index(op.f('ix_reconciliation_logs_pool_id'), table_name='reconciliation_logs')
    op.drop_index(op.f('ix_reconciliation_logs_id'), table_name='reconciliation_logs')
    op.drop_table('reconciliation_logs')
    # ### end Alembic commands ###
