"""add recovery code hash

Revision ID: 902ab28ff6a3
Revises: 7a7b7c7d7e7f
Create Date: 2026-05-18 13:36:57.008974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '902ab28ff6a3'
down_revision: Union[str, Sequence[str], None] = '7a7b7c7d7e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('recovery_code_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recovery_code_hash')
    # ### end Alembic commands ###
