"""Add card_ceiling_limit

Revision ID: a7e53be37adf
Revises: 168c1e8eb186
Create Date: 2026-05-20 23:28:51.189552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7e53be37adf'
down_revision: Union[str, Sequence[str], None] = '168c1e8eb186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_sources', sa.Column('card_ceiling_limit', sa.Numeric(precision=12, scale=2), nullable=True))
    op.execute("UPDATE payment_sources SET card_ceiling_limit = credit_limit WHERE type = 'credit_card'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_sources', 'card_ceiling_limit')
    # ### end Alembic commands ###
