"""add_advanced_credit_and_emi_models

Revision ID: fa0cb382d9bf
Revises: 92fbdc0e1374
Create Date: 2026-05-20 16:01:13.779334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa0cb382d9bf'
down_revision: Union[str, Sequence[str], None] = '92fbdc0e1374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emi_obligations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('remaining_months', sa.Integer(), nullable=False),
    sa.Column('monthly_payment', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['payment_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emi_obligations_id'), 'emi_obligations', ['id'], unique=False)
    op.create_index(op.f('ix_emi_obligations_source_id'), 'emi_obligations', ['source_id'], unique=False)
    op.create_index(op.f('ix_emi_obligations_transaction_id'), 'emi_obligations', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_emi_obligations_user_id'), 'emi_obligations', ['user_id'], unique=False)
    op.create_table('credit_pools',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('pool_type', sa.String(), nullable=False),
    sa.Column('total_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('utilized_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('available_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('statement_day', sa.Integer(), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_pools_id'), 'credit_pools', ['id'], unique=False)
    op.create_index(op.f('ix_credit_pools_user_id'), 'credit_pools', ['user_id'], unique=False)
    op.add_column('payment_sources', sa.Column('credit_pool_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_payment_sources_credit_pool_id'), 'payment_sources', ['credit_pool_id'], unique=False)
    op.create_foreign_key(None, 'payment_sources', 'credit_pools', ['credit_pool_id'], ['id'], ondelete='SET NULL')
    op.add_column('transactions', sa.Column('is_emi', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('transactions', sa.Column('emi_obligation_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_transactions_emi_obligation_id'), 'transactions', ['emi_obligation_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'emi_obligations', ['emi_obligation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_emi_obligation_id'), table_name='transactions')
    op.drop_column('transactions', 'emi_obligation_id')
    op.drop_column('transactions', 'is_emi')
    op.drop_constraint(None, 'payment_sources', type_='foreignkey')
    op.drop_index(op.f('ix_payment_sources_credit_pool_id'), table_name='payment_sources')
    op.drop_column('payment_sources', 'credit_pool_id')
    op.drop_index(op.f('ix_credit_pools_user_id'), table_name='credit_pools')
    op.drop_index(op.f('ix_credit_pools_id'), table_name='credit_pools')
    op.drop_table('credit_pools')
    op.drop_index(op.f('ix_emi_obligations_user_id'), table_name='emi_obligations')
    op.drop_index(op.f('ix_emi_obligations_transaction_id'), table_name='emi_obligations')
    op.drop_index(op.f('ix_emi_obligations_source_id'), table_name='emi_obligations')
    op.drop_index(op.f('ix_emi_obligations_id'), table_name='emi_obligations')
    op.drop_table('emi_obligations')
    # ### end Alembic commands ###
